config/routes.rb
SolidQueueDashboard::Engine.routes.draw do
  resources :jobs, only: [ :index, :show ] do
    member do
      post :retry
    end
  end

  resources :processes, only: [ :index, :show ]

  resources :recurring_tasks, path: "recurring-tasks", only: [ :index, :show ] do
    member do
      post :enqueue
    end
  end

  get "stats", to: "stats#index", as: :stats
  post "appearance/toggle", to: "appearance#toggle", as: :toggle_appearance

  root "dashboard#index"
end

app/controllers/solid_queue_dashboard/appearance_controller.rb
module SolidQueueDashboard
  class AppearanceController < ApplicationController
    def toggle
      cookies[:dark_mode] = cookies[:dark_mode] == "true" ? "false" : "true"
      redirect_to request.referer
    end
  end
end

app/controllers/solid_queue_dashboard/application_controller.rb
module SolidQueueDashboard
  class ApplicationController < ActionController::Base
    include SolidQueueDashboard::PaginationHelper

    layout "solid_queue_dashboard/application"
  end
end

app/controllers/solid_queue_dashboard/dashboard_controller.rb
module SolidQueueDashboard
  class DashboardController < ApplicationController
    def index
      @jobs = SolidQueueDashboard.decorate(SolidQueue::Job.all)
      load_charts
    end

    private

    def load_charts
      case params[:chart_period] || "30m"
      when "15m"
        n = 1
        last = 15
      when "30m"
        n = 1
        last = 30
      when "1h"
        n = 2
        last = 30
      when "3h"
        n = 6
        last = 30
      when "6h"
        n = 12
        last = 30
      when "12h"
        n = 20
        last = 36
      when "1d"
        n = 30
        last = 48
      when "3d"
        n = 90 # 1.5 hours
        last = 48
      when "1w"
        n = 180 # 3 hours
        last = 56
      else
        n = 1
        last = 30
      end

      @charts = [
        {
          name: "Enqueued",
          data: SolidQueue::Job.group_by_minute(:created_at, last: last, n: n).count,
          color: "#A1A1AB"
        },
        {
          name: "Finished",
          data: @jobs.finished.group_by_minute(:finished_at, last: last, n: n).count,
          color: "#23C55E"
        },
        {
          name: "Retried",
          data: @jobs.retried.group_by_minute(:finished_at, last: last, n: n).count,
          color: "#FBBF26"
        },
        {
          name: "Failed",
          data: SolidQueue::FailedExecution.group_by_minute(:created_at, last: last, n: n).count,
          color: "#F04444"
        }
      ]
    end
  end
end

app/controllers/solid_queue_dashboard/jobs_controller.rb
module SolidQueueDashboard
  class JobsController < ApplicationController
    before_action :set_jobs, only: [ :index ]
    before_action :set_job, only: [ :show, :retry ]

    def index
      @job_queue_names = SolidQueueDashboard.job_queue_names
      @job_class_names = SolidQueueDashboard.job_class_names
    end

    def show
      @job_history = SolidQueueDashboard.decorate(
        SolidQueue::Job
          .where.not(id: @job.id)
          .where(class_name: @job.class_name)
          .order(id: :desc)
          .limit(10)
      )
    end

    def retry
      @job.retry
      redirect_to @job, notice: "Job has been scheduled for retry"
    end

    private

    def set_jobs
      jobs = SolidQueue::Job.order(id: :desc)
      jobs = SolidQueueDashboard.decorate(jobs).with_status(params[:status]) if params[:status].present?
      jobs = jobs.where(class_name: params[:class_name]) if params[:class_name].present?
      jobs = jobs.where(queue_name: params[:queue_name]) if params[:queue_name].present?

      @pagination = paginate(jobs, page: params[:page].to_i, per_page: params[:per_page].to_i)
      @jobs = SolidQueueDashboard.decorate(@pagination[:records])
    end

    def set_job
      @job = SolidQueueDashboard.decorate(SolidQueue::Job.find(params[:id]))
    end
  end
end

app/controllers/solid_queue_dashboard/stats_controller.rb
module SolidQueueDashboard
  class StatsController < ApplicationController
    def index
      @jobs = SolidQueueDashboard.decorate(SolidQueue::Job.all)
      @job_class_names = SolidQueueDashboard.job_class_names
    end
  end
end

app/helpers/solid_queue_dashboard/appearance_helper.rb
module SolidQueueDashboard
  module AppearanceHelper
    def dark_mode?
      cookies[:dark_mode] == "true"
    end
  end
end

app/helpers/solid_queue_dashboard/application_helper.rb
module SolidQueueDashboard
  module ApplicationHelper
    def empty_value
      tag.span("—", class: "text-muted-foreground/30")
    end
  end
end

app/helpers/solid_queue_dashboard/icons_helper.rb
module SolidQueueDashboard
  module IconsHelper
    def icon_refresh_cw(options = {})
      svg_options = {
        xmlns: "http://www.w3.org/2000/svg",
        width: "24",
        height: "24",
        viewBox: "0 0 24 24",
        fill: "none",
        stroke: "currentColor",
        "stroke-width": "2",
        "stroke-linecap": "round",
        "stroke-linejoin": "round"
      }.merge(options)

      tag.svg(**svg_options) do
        concat tag.path(d: "M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8")
        concat tag.path(d: "M21 3v5h-5")
        concat tag.path(d: "M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16")
        concat tag.path(d: "M8 16H3v5")
      end
    end

    def icon_triangle_alert(options = {})
      svg_options = {
        xmlns: "http://www.w3.org/2000/svg",
        width: "24",
        height: "24",
        viewBox: "0 0 24 24",
        fill: "none",
        stroke: "currentColor",
        "stroke-width": "2",
        "stroke-linecap": "round",
        "stroke-linejoin": "round"
      }.merge(options)

      tag.svg(**svg_options) do
        concat tag.path(d: "m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3")
        concat tag.path(d: "M12 9v4")
        concat tag.path(d: "M12 17h.01")
      end
    end

    def icon_server(options = {})
      svg_options = {
        xmlns: "http://www.w3.org/2000/svg",
        width: "24",
        height: "24",
        viewBox: "0 0 24 24",
        fill: "none",
        stroke: "currentColor",
        "stroke-width": "2",
        "stroke-linecap": "round",
        "stroke-linejoin": "round"
      }.merge(options)

      tag.svg(**svg_options) do
        concat tag.rect(width: "20", height: "8", x: "2", y: "2", rx: "2", ry: "2")
        concat tag.rect(width: "20", height: "8", x: "2", y: "14", rx: "2", ry: "2")
        concat tag.line(x1: "6", x2: "6.01", y1: "6", y2: "6")
        concat tag.line(x1: "6", x2: "6.01", y1: "18", y2: "18")
      end
    end

    def icon_layout_dashboard(options = {})
      svg_options = {
        xmlns: "http://www.w3.org/2000/svg",
        width: "24",
        height: "24",
        viewBox: "0 0 24 24",
        fill: "none",
        stroke: "currentColor",
        "stroke-width": "2",
        "stroke-linecap": "round",
        "stroke-linejoin": "round"
      }.merge(options)

      tag.svg(**svg_options) do
        concat tag.rect(width: "7", height: "9", x: "3", y: "3", rx: "1")
        concat tag.rect(width: "7", height: "5", x: "14", y: "3", rx: "1")
        concat tag.rect(width: "7", height: "9", x: "14", y: "12", rx: "1")
        concat tag.rect(width: "7", height: "5", x: "3", y: "16", rx: "1")
      end
    end

    def icon_logs(options = {})
      svg_options = {
        xmlns: "http://www.w3.org/2000/svg",
        width: "24",
        height: "24",
        viewBox: "0 0 24 24",
        fill: "none",
        stroke: "currentColor",
        "stroke-width": "2",
        "stroke-linecap": "round",
        "stroke-linejoin": "round"
      }.merge(options)

      tag.svg(**svg_options) do
        concat tag.path(d: "M13 12h8")
        concat tag.path(d: "M13 18h8")
        concat tag.path(d: "M13 6h8")
        concat tag.path(d: "M3 12h1")
        concat tag.path(d: "M3 18h1")
        concat tag.path(d: "M3 6h1")
        concat tag.path(d: "M8 12h1")
        concat tag.path(d: "M8 18h1")
        concat tag.path(d: "M8 6h1")
      end
    end

    def icon_clock(options = {})
      svg_options = {
        xmlns: "http://www.w3.org/2000/svg",
        width: "24",
        height: "24",
        viewBox: "0 0 24 24",
        fill: "none",
        stroke: "currentColor",
        "stroke-width": "2",
        "stroke-linecap": "round",
        "stroke-linejoin": "round"
      }.merge(options)

      tag.svg(**svg_options) do
        concat tag.circle(cx: "12", cy: "12", r: "10")
        concat tag.polyline(points: "12 6 12 12 16 14")
      end
    end

    def icon_github(options = {})
      svg_options = {
        xmlns: "http://www.w3.org/2000/svg",
        width: "24",
        height: "24",
        viewBox: "0 0 24 24",
        fill: "none",
        stroke: "currentColor",
        "stroke-width": "2",
        "stroke-linecap": "round",
        "stroke-linejoin": "round"
      }.merge(options)

      tag.svg(**svg_options) do
        concat tag.path(d: "M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4")
        concat tag.path(d: "M9 18c-4.51 2-5-2-7-2")
      end
    end

    def icon_x(options = {})
      svg_options = {
        xmlns: "http://www.w3.org/2000/svg",
        width: "24",
        height: "24",
        viewBox: "0 0 24 24",
        fill: "none",
        stroke: "currentColor",
        "stroke-width": "2",
        "stroke-linecap": "round",
        "stroke-linejoin": "round"
      }.merge(options)

      tag.svg(**svg_options) do
        concat tag.path(d: "M18 6 6 18")
        concat tag.path(d: "m6 6 12 12")
      end
    end

    def icon_moon(options = {})
      svg_options = {
        xmlns: "http://www.w3.org/2000/svg",
        width: "24",
        height: "24",
        viewBox: "0 0 24 24",
        fill: "none",
        stroke: "currentColor",
        "stroke-width": "2",
        "stroke-linecap": "round",
        "stroke-linejoin": "round"
      }.merge(options)

      tag.svg(**svg_options) do
        concat tag.path(d: "M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z")
      end
    end

    def icon_sun(options = {})
      svg_options = {
        xmlns: "http://www.w3.org/2000/svg",
        width: "24",
        height: "24",
        viewBox: "0 0 24 24",
        fill: "none",
        stroke: "currentColor",
        "stroke-width": "2",
        "stroke-linecap": "round",
        "stroke-linejoin": "round"
      }.merge(options)

      tag.svg(**svg_options) do
        concat tag.circle(cx: "12", cy: "12", r: "4")
        concat tag.path(d: "M12 2v2")
        concat tag.path(d: "M12 20v2")
        concat tag.path(d: "m4.93 4.93 1.41 1.41")
        concat tag.path(d: "m17.66 17.66 1.41 1.41")
        concat tag.path(d: "M2 12h2")
        concat tag.path(d: "M20 12h2")
        concat tag.path(d: "m6.34 17.66-1.41 1.41")
        concat tag.path(d: "m19.07 4.93-1.41 1.41")
      end
    end

    def icon_play(options = {})
      svg_options = {
        xmlns: "http://www.w3.org/2000/svg",
        width: "24",
        height: "24",
        viewBox: "0 0 24 24",
        fill: "none",
        stroke: "currentColor",
        "stroke-width": "2",
        "stroke-linecap": "round",
        "stroke-linejoin": "round"
      }.merge(options)

      tag.svg(**svg_options) do
        concat tag.polygon(points: "6 3 20 12 6 21 6 3")
      end
    end

    def icon_chart_scatter(options = {})
      svg_options = {
        xmlns: "http://www.w3.org/2000/svg",
        width: "24",
        height: "24",
        viewBox: "0 0 24 24",
        fill: "none",
        stroke: "currentColor",
        "stroke-width": "2",
        "stroke-linecap": "round",
        "stroke-linejoin": "round"
      }.merge(options)

      tag.svg(**svg_options) do
        concat tag.circle(cx: "7.5", cy: "7.5", r: ".5", fill: "currentColor")
        concat tag.circle(cx: "18.5", cy: "5.5", r: ".5", fill: "currentColor")
        concat tag.circle(cx: "11.5", cy: "11.5", r: ".5", fill: "currentColor")
        concat tag.circle(cx: "7.5", cy: "16.5", r: ".5", fill: "currentColor")
        concat tag.circle(cx: "17.5", cy: "14.5", r: ".5", fill: "currentColor")
        concat tag.path(d: "M3 3v16a2 2 0 0 0 2 2h16")
      end
    end
  end
end

app/helpers/solid_queue_dashboard/jobs_helper.rb
module SolidQueueDashboard
  module JobsHelper
    def job_status_circle(status, options = {})
      options[:class] = [ "circle", job_status_circle_class(status), options[:class] ].compact_blank.join(" ")
      tag.span("", **options)
    end

    def job_status_circle_class(status)
      {
        "green": "circle-green",
        "amber": "circle-amber",
        "red": "circle-red",
        "blue": "circle-blue",
        "sky": "circle-sky",
        "zinc": "circle-zinc",
        "indigo": "circle-indigo",
        "purple": "circle-purple"
      }[Job::STATUS_COLORS[status]&.to_sym || :zinc]
    end

    def job_status_badge(status, options = {})
      options[:class] = [ "badge", job_status_badge_class(status), options[:class] ].compact_blank.join(" ")
      tag.span(status.to_s.titleize, **options)
    end

    def job_status_badge_class(status)
      {
        "green": "badge-green",
        "amber": "badge-amber",
        "red": "badge-red",
        "blue": "badge-blue",
        "sky": "badge-sky",
        "zinc": "badge-zinc",
        "indigo": "badge-indigo",
        "purple": "badge-purple"
      }[Job::STATUS_COLORS[status]&.to_sym || :zinc]
    end

    def format_failure_rate(failure_rate, options = {})
      badge_variant = case failure_rate
      when 0..1
        "badge-emerald"
      when 1..5
        "badge-amber"
      else
        "badge-red"
      end

      options[:class] = [ "badge", badge_variant, options[:class] ].compact_blank.join(" ")
      tag.span(number_to_percentage(failure_rate, precision: 2, strip_insignificant_zeros: true), **options)
    end

    def any_jobs_filters?
      params[:class_name].present? || params[:status].present? || params[:queue_name].present?
    end
  end
end

app/helpers/solid_queue_dashboard/pagination_helper.rb
module SolidQueueDashboard
  module PaginationHelper
    def paginate(scope, page:, per_page:)
      page = [ page.to_i, 1 ].max
      per_page = per_page.zero? ? 25 : [ per_page.to_i, 1 ].max

      offset = (page - 1) * per_page

      records = scope.offset(offset).limit(per_page)
      total_count = scope.count
      total_pages = (total_count.to_f / per_page).ceil

      {
        records: records,
        current_page: page,
        per_page: per_page,
        total_pages: total_pages,
        total_count: total_count
      }
    end

    def page_range(current_page, total_pages, window: 2)
      if total_pages <= 7
        (1..total_pages).to_a
      else
        [
          1,
          (current_page - window..current_page + window).to_a,
          total_pages
        ].flatten.uniq.sort.reject { |p| p < 1 || p > total_pages }.tap do |range|
          range.each_cons(2) do |a, b|
            range.insert(range.index(b), :gap) if b - a > 1
          end
        end
      end
    end
  end
end

app/helpers/solid_queue_dashboard/processes_helper.rb
module SolidQueueDashboard
  module ProcessesHelper
    def process_kind_circle(kind, options = {})
      options[:class] = [ "circle", process_kind_circle_class(kind), options[:class] ].compact_blank.join(" ")
      tag.span("", **options)
    end

    def process_kind_circle_class(kind)
      {
        "blue": "circle-blue",
        "green": "circle-green",
        "yellow": "circle-yellow",
        "purple": "circle-purple",
        "sky": "circle-sky"
      }[Process::KIND_COLORS[kind]&.to_sym || :zinc]
    end

    def process_kind_badge(kind, options = {})
      options[:class] = [ "badge", process_kind_badge_class(kind), options[:class] ].compact_blank.join(" ")
      tag.span(kind.to_s.titleize, **options)
    end

    def process_kind_badge_class(kind)
      {
        "blue": "badge-blue",
        "green": "badge-green",
        "yellow": "badge-yellow",
        "purple": "badge-purple",
        "sky": "badge-sky"
      }[Process::KIND_COLORS[kind]&.to_sym || :zinc]
    end

    def any_processes_filters?
      params[:kind].present? || params[:hostname].present?
    end
  end
end

app/helpers/solid_queue_dashboard/recurring_tasks_helper.rb
module SolidQueueDashboard
  module RecurringTasksHelper
    def recurring_task_circle(type, options = {})
      options[:class] = [ "circle", recurring_task_circle_class(type), options[:class] ].compact_blank.join(" ")
      tag.span("", **options)
    end

    def recurring_task_circle_class(type)
      {
        "amber": "circle-amber",
        "sky": "circle-sky",
        "zinc": "circle-zinc"
      }[RecurringTask::TYPE_COLORS[type]&.to_sym || :zinc]
    end

    def recurring_task_type_badge(type, options = {})
      options[:class] = [ "badge", recurring_task_type_badge_class(type), options[:class] ].compact_blank.join(" ")
      tag.span(type.to_s.titleize, **options)
    end

    def recurring_task_type_badge_class(type)
      {
        "amber": "badge-amber",
        "sky": "badge-sky",
        "zinc": "badge-zinc"
      }[RecurringTask::TYPE_COLORS[type]&.to_sym || :zinc]
    end

    def any_recurring_tasks_filters?
      params[:class_name].present? || params[:queue_name].present?
    end
  end
end

app/views/solid_queue_dashboard/recurring_tasks/_filters.html.erb
<%= form_with url: recurring_tasks_path, method: :get, class: "space-y-3" do |form| %>
  <div>
    <div class="flex flex-wrap gap-1 mt-1">
      <% SolidQueueDashboard::RecurringTask::TYPES.each do |type| %>
        <%= button_tag type: :submit,
          name: :type,
          value: type,
          class: "px-2 badge #{params[:type] == type.to_s ? 'badge-primary' : 'badge-outline'}" do
        %>
          <%= recurring_task_circle(type) %>
          <%= type.to_s.titleize %>
          <span class="opacity-50 -ml-0.5">
            <%= SolidQueueDashboard.decorate(SolidQueue::RecurringTask.all).with_type(type).count %>
          </span>
        <% end %>
      <% end %>

      <% if params[:type].present? %>
        <%= button_tag type: :submit, name: :type, value: nil, class: "badge badge-destructive gap-1" do %>
          <%= icon_x class: "size-3.5 text-red-500" %>
          Clear
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/solid_queue_dashboard/recurring_tasks/_table.html.erb
<div class="table-wrapper">
  <table class="table">
    <thead class="table-header">
      <tr class="table-row">
        <th class="table-head pl-6">ID</th>
        <th class="table-head">Type</th>
        <th class="table-head"></th>
        <th class="table-head">Schedule</th>
        <th class="table-head">Queue Name</th>
        <th class="table-head">Priority</th>
        <th class="table-head">Key</th>
        <th class="table-head"></th>
      </tr>
    </thead>
    <tbody class="table-body">
      <%= render partial: 'solid_queue_dashboard/recurring_tasks/table_row', collection: recurring_tasks, as: :recurring_task %>
    </tbody>
  </table>
</div>

app/views/solid_queue_dashboard/recurring_tasks/_table_row.html.erb
<tr class="table-row" data-href="<%= recurring_task_path(recurring_task) %>">
  <td class="table-cell pl-6 font-medium text-zinc-900 dark:text-zinc-100">
    <%= recurring_task.id %>
  </td>

  <td class="table-cell">
    <%= recurring_task_type_badge(recurring_task.type) %>
  </td>

  <td class="table-cell">
    <span class="font-medium">
      <%= recurring_task.class_name || recurring_task.command %>
    </span>
  </td>

  <td class="table-cell"><%= recurring_task.schedule %></td>
  <td class="table-cell"><%= recurring_task.queue_name&.titleize || empty_value %></td>
  <td class="table-cell"><%= recurring_task.priority || empty_value %></td>
  <td class="table-cell"><%= recurring_task.key %></td>
  <td class="table-cell">
    <%= form_with url: enqueue_recurring_task_path(recurring_task), method: :post do %>
      <button
        type="submit"
        class="btn btn-md btn-outline"
      >
        <%= icon_play class: "size-4 text-amber-500 mr-1" %>
        Enqueue Now
      </button>
    <% end %>
  </td>
</tr>

app/views/solid_queue_dashboard/recurring_tasks/index.html.erb
<div class="card">
  <div class="card-header border-b">
    <h2 class="card-title">Recurring Tasks</h2>

    <div class="!mt-4">
      <%= render "solid_queue_dashboard/recurring_tasks/filters" %>
    </div>
  </div>

  <div class="card-content !p-0">
    <% if @recurring_tasks.any? %>
      <%= render "solid_queue_dashboard/recurring_tasks/table", recurring_tasks: @recurring_tasks %>
    <% else %>
      <div class="px-6 py-12">
        <p class="text-muted-foreground text-center">
          No recurring tasks found
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/solid_queue_dashboard/recurring_tasks/show.html.erb
<h1 class="text-4xl flex items-center gap-2">
  <%= recurring_task_circle(@recurring_task.type, class: "size-4") %>

  <span class="tracking-tighter font-bold">
    Recurring Task #<%= @recurring_task.id %>
  </span>
</h1>

<div class="card mt-6">
  <div class="card-content pt-6 grid grid-cols-1 sm:grid-cols-2 sm:gap-16">
    <div class="space-y-4">
      <div class="info-line">
        <span class="info-line-label">Type</span>
        <div class="info-line-separator"></div>
        <span class="info-line-value"><%= recurring_task_type_badge(@recurring_task.type) %></span>
      </div>

      <div class="info-line">
        <span class="info-line-label">Key</span>
        <div class="info-line-separator"></div>
        <span class="info-line-value"><%= @recurring_task.key %></span>
      </div>

      <div class="info-line">
        <span class="info-line-label">Schedule</span>
        <div class="info-line-separator"></div>
        <span class="info-line-value"><%= @recurring_task.schedule %></span>
      </div>

      <% if @recurring_task.queue_name? %>
        <div class="info-line">
          <span class="info-line-label">Queue Name</span>
          <div class="info-line-separator"></div>
          <span class="info-line-value"><%= @recurring_task.queue_name %></span>
        </div>
      <% end %>
    </div>

    <div class="space-y-4">
      <% if @recurring_task.priority? %>
        <div class="info-line">
          <span class="info-line-label">Priority</span>
          <div class="info-line-separator"></div>
          <span class="info-line-value"><%= @recurring_task.priority %></span>
        </div>
      <% end %>

      <div class="info-line">
        <span class="info-line-label">Static</span>
        <div class="info-line-separator"></div>
        <span class="info-line-value"><%= @recurring_task.static ? "Yes" : "No" %></span>
      </div>

      <div class="info-line">
        <span class="info-line-label">Created At</span>
        <div class="info-line-separator"></div>
        <span class="info-line-value" data-date><%= @recurring_task.created_at.to_fs(:database) %></span>
      </div>

      <div class="info-line">
        <span class="info-line-label">Updated At</span>
        <div class="info-line-separator"></div>
        <span class="info-line-value" data-date><%= @recurring_task.updated_at.to_fs(:database) %></span>
      </div>
    </div>
  </div>
</div>

<% if @recurring_task.command.present? %>
  <div class="card mt-8 overflow-hidden">
    <div class="card-header border-b border-t-4 border-t-amber-500 dark:border-t-amber-600">
      <h3 class="card-title">Command</h3>
      <p class="card-description">The command to be executed</p>
    </div>
    <div class="card-content pt-6">
      <pre><%= @recurring_task.command %></pre>
    </div>
  </div>
<% end %>

<% if @recurring_task.class_name.present? %>
  <div class="card mt-8 overflow-hidden">
    <div class="card-header border-b border-t-4 border-t-blue-500 dark:border-t-blue-600">
      <h3 class="card-title">Job Class</h3>
      <p class="card-description">The job class to be executed</p>
    </div>
    <div class="card-content pt-6">
      <pre><%= @recurring_task.class_name %></pre>
    </div>
  </div>
<% end %>

<% if @recurring_task.arguments.present? %>
  <div class="card mt-8 overflow-hidden">
    <div class="card-header border-b border-t-4 border-t-purple-500 dark:border-t-purple-600">
      <h3 class="card-title">Arguments</h3>
      <p class="card-description">The arguments to be passed to the job</p>
    </div>
    <div class="card-content pt-6">
      <pre><%= JSON.pretty_generate(@recurring_task.arguments) %></pre>
    </div>
  </div>
<% end %>

<% if @recurring_task.description.present? %>
  <div class="card mt-8 overflow-hidden">
    <div class="card-header border-b border-t-4 border-t-amber-500 dark:border-t-amber-600">
      <h3 class="card-title">Description</h3>
      <p class="card-description">Additional information about this recurring task</p>
    </div>
    <div class="card-content pt-6">
      <pre><%= @recurring_task.description %></pre>
    </div>
  </div>
<% end %>

<div class="card mt-8 overflow-hidden">
  <div class="card-header border-b border-t-4 border-t-zinc-500 dark:border-t-zinc-600">
    <h3 class="card-title">Next Runs</h3>
    <p class="card-description">Based on the current schedule</p>
  </div>
  <div class="card-content pt-5">
    <ul class="list-decimal marker:text-sm marker:text-muted-foreground ml-4 space-y-1">
      <% @recurring_task.next_runs.each do |run_time| %>
        <li>
          <span data-date><%= run_time.strftime("%Y-%m-%d %H:%M:%S %Z") %></span>
          <span class="text-muted-foreground">
            in <%= distance_of_time_in_words(Time.current, run_time) %>
          </span>
        </li>
      <% end %>
    </ul>
  </div>
</div>